
WIN_WIDTH = 1920
WIN_HEIGHT = 1200
GRID_WIDTH = 48
GRID_HEIGHT = 30
AGENTS_AMT = 100

IMAGE_SCALE = 10

# Station Generation
STATION_COVERAGE_RADIUS = 5
STATIONS_AMT = 8
STATION_GEN_FILE_NAME = 'stations_gen.csv'
STATIONS_GEN_REFINE_MAX = 10

# Train Generation
TRAINS_AMT = 3
MIN_STATIONS_P_TRAIN = 3
MAX_STATIONS_P_TRAIN = 6
MAX_TRAINS_P_STATION = 3
STATIONS_FILE = 'stations_gen.csv'
TRAINS_FILE = 'trains_gen.csv'

CON_DISTANCE_MAX_PERCENT = 50